import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import FooterSection from "@/components/layouts/footer";


const spaceGrotesk = localFont({
  src: [
    {
      path: "./../public/fonts/SpaceGrotesk-Bold.ttf", 
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-space",
});

export const metadata: Metadata = {
  title: "Unlie Dasboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable}`}>
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
